server:
  port: 8001
#security:
#  sessions: stateless
#  basic:
#    enabled: true # 启用SpringSecurity的安全配置项
#  user:
#    name: root  # 认证用户名
#    password: hello # 认证密码
#    role:        # 授权角色
#    - USER
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/j2ee?useUnicode=true&characterEncoding=utf8           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 123456                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间